#!/usr/bin/env node
// Tells IndexNow-enabled search engines (Bing, Yandex, Seznam, Naver...) that every
// sitemap URL changed. Bing's index also feeds Copilot and ChatGPT search.
// The key file /<key>.txt is generated by the build and must be live first.
import { site } from "../src/site.mjs";
import { pages } from "../src/pages/index.mjs";

const urlList = pages.filter((p) => p.sitemap !== false && !p.noindex).map((p) => site.url + p.path);
const res = await fetch("https://api.indexnow.org/indexnow", {
  method: "POST",
  headers: { "content-type": "application/json; charset=utf-8" },
  body: JSON.stringify({
    host: site.domain,
    key: site.indexNowKey,
    keyLocation: `${site.url}/${site.indexNowKey}.txt`,
    urlList,
  }),
});
console.log(`IndexNow: HTTP ${res.status} for ${urlList.length} URLs`);
if (res.status >= 400) process.exit(1);
